[mqtt_subsciber]
    broker = "10.247.56.153"
    port = 1883

[[mqtt_subsciber.subscription]]
    topic="power_monitoring/#"

#[[mqtt_subsciber.subscription]]
#    topic="other/topic"

[[mapper.topic]]
    pattern = "#" #accepts wildcards: '+' for single level and '#' for anything thereafter
#    local_prefix = "local/prefix"
    remote_prefix = "cambridge_lab2"

[mqtt_publisher]
    broker = "192.168.56.108"
    port = 8883   #common mqtt ports are 1883 and 8883
    base_topic_template = ""

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds