apiVersion: 1

datasources:
  - name: Data Storage Module
    type: marcusolsson-json-datasource
    version: 1
    editable: true
    access: proxy
    url: http://data-storage.docker.local:80
    uid: json_api
  - name: MQTT Direct
    type: grafana-mqtt-datasource
    version: 1
    editable: true
    access: proxy
    uid: mqtt_direct
    jsonData:
      uri: tcp://mqtt.docker.local:1883
