
services:
    stoppage-dc:
        extends:
            file: user_input/app.yml
            service: dev
        networks:
            internal:
                aliases:
                    - stoppage-dc.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-stoppage-dc
        restart: unless-stopped
        depends_on:
            - "data-storage"
    data-storage:
        extends:
            file: data_storage/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - data-storage.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-data-storage
        restart: unless-stopped
        env_file:
            - django_secret_key 
            - default_password
   
    mqtt_broker:
        extends:
            file: mqtt_broker/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - mqtt.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-mqtt-broker
        restart: unless-stopped
    dashboard:
        extends:
            file: dashboard_ui/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - dashboard-ui.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-dashboard-ui
        restart: unless-stopped
        depends_on:
            - "data-storage"
            

    sensor-adaptor:
        extends:
            file: ./sensor_adaptor/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - sensor-adaptor.docker.local

        logging:
            driver: syslog
            options:
                tag: docker-sensor-adaptor
        restart: unless-stopped       

networks:
    internal:
      name: shoestring-internal
