
services:
    stoppage-dc:
        extends:
            file: user_input/app.yml
            service: dev
        networks:
            internal:
                aliases:
                    - stoppage-dc.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-stoppage-dc
        restart: unless-stopped
        depends_on:
            - "data-storage"
    # reasons-sds:
    #     extends:
    #         file: reasons_sds/app.yml
    #         service: app
    #     networks:
    #         internal:
    #             aliases:
    #                 - reasons-sds.docker.local
    #     logging:
    #             driver: syslog
    #             options:
    #                     tag: docker-reasons-sds
    #     restart: unless-stopped
    #     env_file:
    #         - django_secret_key 

    data-storage:
        extends:
            file: data_storage/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - data-storage.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-data-storage
        restart: unless-stopped
        env_file:
            - django_secret_key 
            - default_password

    # reason-events:
    #     extends:
    #         file: auto_reason_control_sm/app.yml
    #         service: app
    #     networks:
    #         internal:
    #             aliases:
    #                 - reason-events.docker.local
    #     logging:
    #             driver: syslog
    #             options:
    #                     tag: docker-reason-events
    #     restart: unless-stopped
 
    timeseries-db:
        extends:
            file: timeseries_sds/app.yml
            service: db
        networks:
            internal:
                aliases:
                    - timeseries-db.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-timeseries-db
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
    # timeseries-db-input:
    #     extends:
    #         file: timeseries_sds/app.yml
    #         service: telegraf
    #     networks:
    #         internal:
    #             aliases:
    #                 - timeseries-input.docker.local
    #     logging:
    #         driver: syslog
    #         options:
    #             tag: docker-timeseries-input
    #     restart: unless-stopped
    #     depends_on:
    #         - "timeseries-db"
    #         - "mqtt_broker"
    mqtt_broker:
        extends:
            file: mqtt_broker/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - mqtt.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-mqtt-broker
        restart: unless-stopped
    dashboard:
        extends:
            file: dashboard_ui/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - dashboard-ui.docker.local
        logging:
                driver: syslog
                options:
                        tag: docker-dashboard-ui
        restart: unless-stopped
        depends_on:
            - "data-storage"
networks:
    internal:
      name: shoestring-internal
