#   Select the config file (by removing the leading #) appropriate for your hardware and wiring setup
#
module_config_file = "./config/ddowntime.toml"


#   Set the machine name
calculation.machine_name.config.machine = "Machine_Name_Here"
