# Generated by Django 5.0.6 on 2025-03-04 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('enable_manual_input', models.BooleanField(default=True, help_text='If set to true, the machines status can be set manually in the user interface')),
                ('enable_historic_manual_input', models.BooleanField(default=False, help_text='If set to true, users can insert new downtime events into the history')),
                ('enable_edit_manual_input', models.BooleanField(default=True, help_text='If set to true, users can edit past events that were created manually')),
                ('enable_delete_manual_input', models.BooleanField(default=True, help_text='If set to true, users can delete past events that were created manually')),
                ('enable_edit_sensor_input', models.BooleanField(default=False, help_text='If set to true, users can edit past events that were created by sensor inputs')),
                ('enable_delete_sensor_input', models.BooleanField(default=False, help_text='If set to true, users can delete past events that were created by sensor inputs')),
                ('enable_historic_sensor_input', models.BooleanField(default=False, help_text='If set to true, sensor inputs with timestamps in the past (before the latest event) will be inserted, updating the history, if false they will be ignored')),
            ],
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('running', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(blank=True, choices=[('sensor', 'Sensor'), ('user', 'User')], max_length=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event Records',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('running', models.BooleanField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('previous_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_entry', to='state.state')),
            ],
            options={
                'verbose_name_plural': 'State Records',
            },
        ),
    ]
