# Generated by Django 5.0.6 on 2025-02-11 11:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('sensor', models.BooleanField(default=False, help_text='Set to true if running status is based on a sensor value')),
            ],
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('running', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(blank=True, choices=[('sensor', 'Sensor'), ('user', 'User')], max_length=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event Records',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('running', models.BooleanField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('previous_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_entry', to='state.state')),
            ],
            options={
                'verbose_name_plural': 'State Records',
            },
        ),
    ]
