# Generated by Django 5.0.6 on 2025-02-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
        ('stop_reasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stop_reasons.reason'),
        ),
        migrations.AddField(
            model_name='state',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_records', to='state.machine'),
        ),
        migrations.AddField(
            model_name='statusevent',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_records', to='state.machine'),
        ),
        migrations.AddField(
            model_name='state',
            name='trigger_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resulting_state', to='state.statusevent'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['-start', '-end'], name='timestamp_idx'),
        ),
    ]
