# Generated by Django 5.0.6 on 2025-02-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='trigger_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resulting_state', to='state.statusevent'),
        ),
    ]
