# Generated by Django 5.0.6 on 2025-02-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_alter_state_trigger_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusevent',
            name='occured_during',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_during', to='state.state'),
        ),
    ]
