# Generated by Django 5.0.6 on 2025-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_statusevent_occured_during'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='sensor',
        ),
        migrations.AddField(
            model_name='machine',
            name='edit_manual_input',
            field=models.BooleanField(default=True, help_text='If set to true, users can edit or delete past events that were created manually'),
        ),
        migrations.AddField(
            model_name='machine',
            name='edit_sensor_input',
            field=models.BooleanField(default=False, help_text='If set to true, users can edit or delete past events that were created by sensor inputs'),
        ),
        migrations.AddField(
            model_name='machine',
            name='manual_input',
            field=models.BooleanField(default=True, help_text='If set to true, the machines status can be set manually in the user interface'),
        ),
    ]
