# Generated by Django 5.0.6 on 2025-02-25 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_statusevent_next_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusevent',
            name='next_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_entry', to='state.statusevent'),
        ),
    ]
