# Generated by Django 5.0.6 on 2025-02-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=60)),
                ('colour', models.CharField(choices=[('#4CAF50', 'Green'), ('#00E5FF', 'Blue'), ('#D50000', 'Red'), ('#FF6F00', 'Orange'), ('#6200EA', 'Purple'), ('#03DAC5', 'Turquoise'), ('#FF0266', 'Pink'), ('#FFD600', 'Yellow')], default='#00E5FF', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MachineReasonMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=60)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stop_reasons.category')),
                ('machine_mapping', models.ManyToManyField(related_name='reason_mapping', through='stop_reasons.MachineReasonMap', to='state.machine')),
            ],
        ),
        migrations.AddField(
            model_name='machinereasonmap',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop_reasons.reason'),
        ),
    ]
