# Generated by Django 5.0.6 on 2025-02-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop_reasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='considered_downtime',
            field=models.BooleanField(default=True, help_text="Untick for reasons (like end of shift) that shouldn't be considered for Downtime"),
        ),
    ]
