[mqtt_subsciber]
    broker = "192.168.56.108"
    port = 1883

[[mqtt_subsciber.subscription]]
    topic="equipment_monitoring/status/#"

#[[mqtt_subsciber.subscription]]
#    topic="other/topic"

[state_model]

[mqtt_publisher]
    broker = "192.168.56.108"
    port = 1883   #common mqtt ports are 1883 and 8883
    base_topic_template = ""

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds
